site_name: APan MkDocs
theme:
  name: material
  icon:
    logo: material/snowflake-variant       # sigma/panda/roman-numeral-9/snowflake-variant
  favicon: assets/snowflake-variant.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky   # keeps tabs visible when scrolling
    - navigation.sections      # groups sidebar items into labeled sections
    - navigation.top           # adds a "back to top" button
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Tech:
      - Overview: tech/index.md
      - MkDocs Setup: tech/mkdocs-setup.md
  - Note:
      - On this site: note/index.md
  - About:
      - This site: about/index.md
