site_name: APan MkDocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list   # for extra CSS
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    logo: material/snowflake-variant       # sigma/panda/roman-numeral-9/snowflake-variant
  favicon: assets/snowflake-variant.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky   # keeps tabs visible when scrolling
    - navigation.indexes       # lets a folder's index.md serve as its landing page
    # - navigation.sections      # groups sidebar items into labeled sections
    - navigation.top           # adds a "back to top" button
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Blog:
      - 2034: blog/2034.md
      - 2026: blog/2026.md
  - Tech:
      - Overview: tech/index.md
      - MkDocs Setup: tech/mkdocs-setup.md
      - MkDocs: tech/mkdocs.md
      - GitHub: 
          - workflow: tech/workflow.md
      - Bash:
          - one-liner: tech/one-liner-bash.md
      - Python:
          - one-liner: tech/one-liner-python.md
  - Note:
      - Notes: note/index.md
  - About:
      - This site: about/index.md
  - 日志:
      - 备忘: 
          - 金婚: blogc/golden-merriage.md
      - 2026: blogc/2026.md
